title: LEHS
email: perolehs@gmail.com
description: >
  A another simple person in the universe.
url: "https://perolehs.github.io" 
twitter_username:
github_username: perolehs
# theme: minima
excerpt_separator: <!--more-->
plugins:
  - jekyll-paginate-v2
  - jekyll-feed
sass:
  style: compressed
pagination:
  enabled: true
  per_page: 5
